In [1]:
pip install numpy

     ---------------------------------------- 12.6/12.6 MB 4.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python311\\Scripts\\f2py.exe' -> 'C:\\Python311\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [4]:
rand_arr = np.random.randint(1,50,size = (1,10))

In [5]:
rand_arr

array([[10, 31, 24, 45, 17, 47, 29, 36, 44, 34]], dtype=int32)

In [6]:
rand_arr.size

10

In [7]:
np.shape(rand_arr)

(1, 10)

In [8]:
rand_arr.dtype

dtype('int32')

2

In [9]:
two_d_arr = np.random.randint(10,100,size = (2,5))

In [10]:
two_d_arr

array([[92, 19, 36, 77, 84],
       [44, 41, 20, 90, 20]], dtype=int32)

## home work

In [11]:
arr = np.random.randint(1,50 ,size =(1,10))

In [12]:
np.mean(arr)

np.float64(26.6)

In [13]:
arr

array([[21, 38, 34, 44, 45,  1, 18, 21, 33, 11]], dtype=int32)

## 2

In [15]:
mat1 = np.array([[1,2,3],[4,5,6],[6,7,8]])
mat2 = np.array([[11,22,31],[54,75,69],[46,37,28]])
res = mat1 + mat2
np.mean(res)

np.float64(46.111111111111114)

## 3

In [16]:
arr3 = np.random.randint(1,100 ,size =(1,20))

In [17]:
arr3

array([[ 3, 67, 68, 53, 90,  8, 82,  7, 84, 30, 99, 86,  6, 15, 31, 52,
        39, 17, 70, 87]], dtype=int32)

In [18]:
bigger = arr3[arr3 > 50]

In [19]:
bigger

array([67, 68, 53, 90, 82, 84, 99, 86, 52, 70, 87], dtype=int32)

## 4

In [20]:
arr4 = np.random.randint(1,50 ,size =(1,10))

In [21]:
res4 = arr4.reshape(5,2)

In [22]:
arr4

array([[23, 39, 23, 19,  7, 48, 12,  9, 14, 10]], dtype=int32)

In [23]:
res4

array([[23, 39],
       [23, 19],
       [ 7, 48],
       [12,  9],
       [14, 10]], dtype=int32)

In [24]:
res4[3][1]

np.int32(9)